sudo: required

language: go

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker build -t ${DOCKER_USERNAME}/janna-slack-bot:${COMMIT} .
        - docker images
        - docker tag ${DOCKER_USERNAME}/janna-slack-bot:${COMMIT} ${DOCKER_USERNAME}/janna-slack-bot:latest

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push ${DOCKER_USERNAME}/janna-slack-bot:${COMMIT};
      docker push ${DOCKER_USERNAME}/janna-slack-bot:latest;
    fi
